import type { PlayerPosition } from "../../src/generated/prisma/enums";

export type SeedPlayer = {
  name: string;
  position: PlayerPosition;
  team: string;
  /** Weekly scoring mean and spread. Drives which players become legends. */
  mean: number;
  stdDev: number;
};

/** Roster pool. Means are rough PPR weekly averages — the point is that stars
 *  reliably outscore depth, so generated records land on believable names. */
export const PLAYERS: SeedPlayer[] = [
  // Quarterbacks
  { name: "Josh Allen", position: "QB", team: "BUF", mean: 24.5, stdDev: 7.5 },
  { name: "Lamar Jackson", position: "QB", team: "BAL", mean: 24.0, stdDev: 7.8 },
  { name: "Jalen Hurts", position: "QB", team: "PHI", mean: 22.8, stdDev: 7.0 },
  { name: "Patrick Mahomes", position: "QB", team: "KC", mean: 21.5, stdDev: 6.2 },
  { name: "Joe Burrow", position: "QB", team: "CIN", mean: 21.8, stdDev: 6.8 },
  { name: "Jayden Daniels", position: "QB", team: "WAS", mean: 21.0, stdDev: 7.2 },
  { name: "Justin Herbert", position: "QB", team: "LAC", mean: 19.0, stdDev: 5.8 },
  { name: "C.J. Stroud", position: "QB", team: "HOU", mean: 18.6, stdDev: 6.0 },
  { name: "Jordan Love", position: "QB", team: "GB", mean: 18.2, stdDev: 6.4 },
  { name: "Dak Prescott", position: "QB", team: "DAL", mean: 18.0, stdDev: 6.1 },
  { name: "Brock Purdy", position: "QB", team: "SF", mean: 18.4, stdDev: 6.0 },
  { name: "Kyler Murray", position: "QB", team: "ARI", mean: 18.8, stdDev: 6.6 },
  { name: "Tua Tagovailoa", position: "QB", team: "MIA", mean: 17.4, stdDev: 6.3 },
  { name: "Baker Mayfield", position: "QB", team: "TB", mean: 18.1, stdDev: 6.5 },
  { name: "Caleb Williams", position: "QB", team: "CHI", mean: 16.8, stdDev: 6.4 },
  { name: "Trevor Lawrence", position: "QB", team: "JAX", mean: 16.2, stdDev: 6.0 },

  // Running backs
  { name: "Christian McCaffrey", position: "RB", team: "SF", mean: 21.5, stdDev: 8.2 },
  { name: "Saquon Barkley", position: "RB", team: "PHI", mean: 20.8, stdDev: 8.6 },
  { name: "Bijan Robinson", position: "RB", team: "ATL", mean: 19.4, stdDev: 7.4 },
  { name: "Jahmyr Gibbs", position: "RB", team: "DET", mean: 19.0, stdDev: 7.8 },
  { name: "Derrick Henry", position: "RB", team: "BAL", mean: 18.2, stdDev: 8.0 },
  { name: "Breece Hall", position: "RB", team: "NYJ", mean: 16.8, stdDev: 6.8 },
  { name: "Jonathan Taylor", position: "RB", team: "IND", mean: 16.4, stdDev: 7.0 },
  { name: "Josh Jacobs", position: "RB", team: "GB", mean: 16.0, stdDev: 6.4 },
  { name: "De'Von Achane", position: "RB", team: "MIA", mean: 16.6, stdDev: 8.4 },
  { name: "Kyren Williams", position: "RB", team: "LAR", mean: 15.8, stdDev: 6.0 },
  { name: "James Cook", position: "RB", team: "BUF", mean: 15.2, stdDev: 6.6 },
  { name: "Kenneth Walker III", position: "RB", team: "SEA", mean: 14.6, stdDev: 6.5 },
  { name: "Bucky Irving", position: "RB", team: "TB", mean: 14.0, stdDev: 6.2 },
  { name: "Chase Brown", position: "RB", team: "CIN", mean: 13.8, stdDev: 6.4 },
  { name: "Alvin Kamara", position: "RB", team: "NO", mean: 15.4, stdDev: 6.8 },
  { name: "Joe Mixon", position: "RB", team: "HOU", mean: 14.2, stdDev: 6.0 },
  { name: "David Montgomery", position: "RB", team: "DET", mean: 13.4, stdDev: 6.2 },
  { name: "Travis Etienne Jr.", position: "RB", team: "JAX", mean: 12.8, stdDev: 5.8 },
  { name: "Isiah Pacheco", position: "RB", team: "KC", mean: 12.6, stdDev: 5.6 },
  { name: "Aaron Jones", position: "RB", team: "MIN", mean: 13.2, stdDev: 6.0 },
  { name: "Tony Pollard", position: "RB", team: "TEN", mean: 12.4, stdDev: 5.4 },
  { name: "Najee Harris", position: "RB", team: "PIT", mean: 12.2, stdDev: 5.2 },
  { name: "Rachaad White", position: "RB", team: "TB", mean: 11.8, stdDev: 5.6 },

  // Wide receivers
  { name: "Ja'Marr Chase", position: "WR", team: "CIN", mean: 19.8, stdDev: 8.4 },
  { name: "Justin Jefferson", position: "WR", team: "MIN", mean: 19.2, stdDev: 7.8 },
  { name: "CeeDee Lamb", position: "WR", team: "DAL", mean: 18.4, stdDev: 7.6 },
  { name: "Amon-Ra St. Brown", position: "WR", team: "DET", mean: 17.6, stdDev: 6.8 },
  { name: "Puka Nacua", position: "WR", team: "LAR", mean: 17.0, stdDev: 7.4 },
  { name: "A.J. Brown", position: "WR", team: "PHI", mean: 16.8, stdDev: 8.0 },
  { name: "Tyreek Hill", position: "WR", team: "MIA", mean: 16.4, stdDev: 8.6 },
  { name: "Nico Collins", position: "WR", team: "HOU", mean: 16.2, stdDev: 7.2 },
  { name: "Malik Nabers", position: "WR", team: "NYG", mean: 15.8, stdDev: 7.0 },
  { name: "Drake London", position: "WR", team: "ATL", mean: 15.4, stdDev: 6.8 },
  { name: "Garrett Wilson", position: "WR", team: "NYJ", mean: 15.0, stdDev: 6.6 },
  { name: "Mike Evans", position: "WR", team: "TB", mean: 15.2, stdDev: 7.8 },
  { name: "Brian Thomas Jr.", position: "WR", team: "JAX", mean: 14.8, stdDev: 7.2 },
  { name: "Davante Adams", position: "WR", team: "LAR", mean: 14.6, stdDev: 7.0 },
  { name: "DK Metcalf", position: "WR", team: "PIT", mean: 14.0, stdDev: 7.4 },
  { name: "Marvin Harrison Jr.", position: "WR", team: "ARI", mean: 13.8, stdDev: 6.8 },
  { name: "Terry McLaurin", position: "WR", team: "WAS", mean: 14.2, stdDev: 6.6 },
  { name: "Jaylen Waddle", position: "WR", team: "MIA", mean: 13.4, stdDev: 6.4 },
  { name: "DeVonta Smith", position: "WR", team: "PHI", mean: 13.6, stdDev: 6.2 },
  { name: "Chris Olave", position: "WR", team: "NO", mean: 13.2, stdDev: 6.4 },
  { name: "Tee Higgins", position: "WR", team: "CIN", mean: 13.8, stdDev: 6.8 },
  { name: "Ladd McConkey", position: "WR", team: "LAC", mean: 13.0, stdDev: 6.0 },
  { name: "Zay Flowers", position: "WR", team: "BAL", mean: 12.8, stdDev: 5.8 },
  { name: "Courtland Sutton", position: "WR", team: "DEN", mean: 12.6, stdDev: 6.2 },
  { name: "Jordan Addison", position: "WR", team: "MIN", mean: 12.2, stdDev: 6.0 },
  { name: "Rome Odunze", position: "WR", team: "CHI", mean: 11.8, stdDev: 5.8 },
  { name: "Khalil Shakir", position: "WR", team: "BUF", mean: 11.4, stdDev: 5.2 },
  { name: "Cooper Kupp", position: "WR", team: "SEA", mean: 12.4, stdDev: 6.4 },
  { name: "Calvin Ridley", position: "WR", team: "TEN", mean: 11.6, stdDev: 6.0 },
  { name: "DJ Moore", position: "WR", team: "CHI", mean: 12.8, stdDev: 6.2 },
  { name: "Jameson Williams", position: "WR", team: "DET", mean: 11.8, stdDev: 6.6 },
  { name: "Jerry Jeudy", position: "WR", team: "CLE", mean: 11.2, stdDev: 5.6 },
  { name: "Jakobi Meyers", position: "WR", team: "LV", mean: 10.8, stdDev: 5.0 },
  { name: "Rashee Rice", position: "WR", team: "KC", mean: 12.0, stdDev: 5.8 },

  // Tight ends
  { name: "Brock Bowers", position: "TE", team: "LV", mean: 14.2, stdDev: 5.8 },
  { name: "Trey McBride", position: "TE", team: "ARI", mean: 13.4, stdDev: 5.4 },
  { name: "George Kittle", position: "TE", team: "SF", mean: 13.0, stdDev: 6.0 },
  { name: "Sam LaPorta", position: "TE", team: "DET", mean: 11.8, stdDev: 5.2 },
  { name: "Mark Andrews", position: "TE", team: "BAL", mean: 11.4, stdDev: 5.6 },
  { name: "Travis Kelce", position: "TE", team: "KC", mean: 12.2, stdDev: 5.4 },
  { name: "T.J. Hockenson", position: "TE", team: "MIN", mean: 10.6, stdDev: 4.8 },
  { name: "David Njoku", position: "TE", team: "CLE", mean: 10.2, stdDev: 5.0 },
  { name: "Evan Engram", position: "TE", team: "DEN", mean: 9.8, stdDev: 4.6 },
  { name: "Jake Ferguson", position: "TE", team: "DAL", mean: 9.4, stdDev: 4.4 },
  { name: "Dallas Goedert", position: "TE", team: "PHI", mean: 9.6, stdDev: 4.8 },
  { name: "Kyle Pitts", position: "TE", team: "ATL", mean: 8.8, stdDev: 5.0 },
  { name: "Dalton Kincaid", position: "TE", team: "BUF", mean: 8.6, stdDev: 4.4 },
  { name: "Tucker Kraft", position: "TE", team: "GB", mean: 8.4, stdDev: 4.2 },

  // Kickers
  { name: "Brandon Aubrey", position: "K", team: "DAL", mean: 10.4, stdDev: 3.8 },
  { name: "Jake Elliott", position: "K", team: "PHI", mean: 9.2, stdDev: 3.4 },
  { name: "Chris Boswell", position: "K", team: "PIT", mean: 9.8, stdDev: 3.6 },
  { name: "Harrison Butker", position: "K", team: "KC", mean: 9.0, stdDev: 3.4 },
  { name: "Cameron Dicker", position: "K", team: "LAC", mean: 9.4, stdDev: 3.5 },
  { name: "Tyler Bass", position: "K", team: "BUF", mean: 8.6, stdDev: 3.3 },
  { name: "Younghoe Koo", position: "K", team: "ATL", mean: 8.2, stdDev: 3.2 },
  { name: "Jason Sanders", position: "K", team: "MIA", mean: 8.0, stdDev: 3.2 },
  { name: "Ka'imi Fairbairn", position: "K", team: "HOU", mean: 8.8, stdDev: 3.4 },
  { name: "Justin Tucker", position: "K", team: "BAL", mean: 9.6, stdDev: 3.5 },

  // Team defenses
  { name: "Ravens D/ST", position: "DST", team: "BAL", mean: 8.4, stdDev: 5.2 },
  { name: "Broncos D/ST", position: "DST", team: "DEN", mean: 8.8, stdDev: 5.6 },
  { name: "Eagles D/ST", position: "DST", team: "PHI", mean: 8.2, stdDev: 5.0 },
  { name: "Steelers D/ST", position: "DST", team: "PIT", mean: 8.6, stdDev: 5.4 },
  { name: "Vikings D/ST", position: "DST", team: "MIN", mean: 8.0, stdDev: 5.2 },
  { name: "Bills D/ST", position: "DST", team: "BUF", mean: 7.6, stdDev: 4.8 },
  { name: "Texans D/ST", position: "DST", team: "HOU", mean: 7.4, stdDev: 5.0 },
  { name: "Packers D/ST", position: "DST", team: "GB", mean: 7.2, stdDev: 4.8 },
  { name: "Chargers D/ST", position: "DST", team: "LAC", mean: 7.8, stdDev: 5.0 },
  { name: "Lions D/ST", position: "DST", team: "DET", mean: 6.8, stdDev: 4.6 },
  { name: "Seahawks D/ST", position: "DST", team: "SEA", mean: 6.6, stdDev: 4.6 },
  { name: "Chiefs D/ST", position: "DST", team: "KC", mean: 7.0, stdDev: 4.8 },

  // Depth. A 12-team league drafts ~170 players, and bench spots need real
  // names so waiver-wire memories don't read like placeholder text.
  { name: "Sam Darnold", position: "QB", team: "SEA", mean: 15.4, stdDev: 6.0 },
  { name: "Geno Smith", position: "QB", team: "LV", mean: 15.0, stdDev: 5.6 },
  { name: "Bo Nix", position: "QB", team: "DEN", mean: 16.4, stdDev: 6.2 },
  { name: "Drake Maye", position: "QB", team: "NE", mean: 15.8, stdDev: 6.4 },
  { name: "Anthony Richardson", position: "QB", team: "IND", mean: 15.2, stdDev: 8.0 },
  { name: "Russell Wilson", position: "QB", team: "NYG", mean: 14.2, stdDev: 5.8 },
  { name: "Aaron Rodgers", position: "QB", team: "PIT", mean: 14.6, stdDev: 5.4 },
  { name: "Matthew Stafford", position: "QB", team: "LAR", mean: 16.0, stdDev: 5.6 },
  { name: "Kirk Cousins", position: "QB", team: "ATL", mean: 14.0, stdDev: 5.4 },
  { name: "Michael Penix Jr.", position: "QB", team: "ATL", mean: 14.8, stdDev: 6.2 },
  { name: "Will Levis", position: "QB", team: "TEN", mean: 13.2, stdDev: 6.0 },
  { name: "Bryce Young", position: "QB", team: "CAR", mean: 13.8, stdDev: 6.2 },

  { name: "Omarion Hampton", position: "RB", team: "LAC", mean: 12.0, stdDev: 5.6 },
  { name: "Ashton Jeanty", position: "RB", team: "LV", mean: 13.6, stdDev: 6.4 },
  { name: "TreVeyon Henderson", position: "RB", team: "NE", mean: 11.4, stdDev: 5.8 },
  { name: "Quinshon Judkins", position: "RB", team: "CLE", mean: 11.0, stdDev: 5.4 },
  { name: "Tyrone Tracy Jr.", position: "RB", team: "NYG", mean: 11.2, stdDev: 5.2 },
  { name: "Jaylen Warren", position: "RB", team: "PIT", mean: 10.8, stdDev: 4.8 },
  { name: "Rhamondre Stevenson", position: "RB", team: "NE", mean: 10.6, stdDev: 5.0 },
  { name: "Javonte Williams", position: "RB", team: "DAL", mean: 10.4, stdDev: 5.2 },
  { name: "Zach Charbonnet", position: "RB", team: "SEA", mean: 10.2, stdDev: 5.6 },
  { name: "Tyjae Spears", position: "RB", team: "TEN", mean: 9.8, stdDev: 4.8 },
  { name: "Brian Robinson Jr.", position: "RB", team: "SF", mean: 9.6, stdDev: 4.6 },
  { name: "Rico Dowdle", position: "RB", team: "CAR", mean: 10.0, stdDev: 5.4 },
  { name: "Jordan Mason", position: "RB", team: "MIN", mean: 9.4, stdDev: 5.0 },
  { name: "Tank Bigsby", position: "RB", team: "PHI", mean: 8.8, stdDev: 4.8 },
  { name: "Ray Davis", position: "RB", team: "BUF", mean: 8.2, stdDev: 4.4 },
  { name: "Blake Corum", position: "RB", team: "LAR", mean: 7.8, stdDev: 4.2 },
  { name: "Kimani Vidal", position: "RB", team: "LAC", mean: 7.4, stdDev: 4.0 },
  { name: "Roschon Johnson", position: "RB", team: "CHI", mean: 7.2, stdDev: 4.2 },
  { name: "Kareem Hunt", position: "RB", team: "KC", mean: 8.6, stdDev: 4.6 },
  { name: "Austin Ekeler", position: "RB", team: "WAS", mean: 8.4, stdDev: 4.4 },
  { name: "Nick Chubb", position: "RB", team: "HOU", mean: 9.0, stdDev: 4.8 },
  { name: "J.K. Dobbins", position: "RB", team: "DEN", mean: 10.6, stdDev: 5.4 },
  { name: "Chuba Hubbard", position: "RB", team: "CAR", mean: 11.6, stdDev: 5.2 },

  { name: "Xavier Worthy", position: "WR", team: "KC", mean: 11.6, stdDev: 6.0 },
  { name: "Tetairoa McMillan", position: "WR", team: "CAR", mean: 11.0, stdDev: 5.8 },
  { name: "Travis Hunter", position: "WR", team: "JAX", mean: 11.2, stdDev: 6.2 },
  { name: "Emeka Egbuka", position: "WR", team: "TB", mean: 10.8, stdDev: 5.6 },
  { name: "Jaxon Smith-Njigba", position: "WR", team: "SEA", mean: 13.4, stdDev: 6.2 },
  { name: "Keon Coleman", position: "WR", team: "BUF", mean: 10.2, stdDev: 5.8 },
  { name: "Ricky Pearsall", position: "WR", team: "SF", mean: 10.4, stdDev: 5.4 },
  { name: "Josh Downs", position: "WR", team: "IND", mean: 10.0, stdDev: 5.0 },
  { name: "Wan'Dale Robinson", position: "WR", team: "NYG", mean: 9.8, stdDev: 4.6 },
  { name: "Darnell Mooney", position: "WR", team: "ATL", mean: 10.6, stdDev: 5.4 },
  { name: "Chris Godwin", position: "WR", team: "TB", mean: 12.2, stdDev: 5.8 },
  { name: "Amari Cooper", position: "WR", team: "LV", mean: 10.4, stdDev: 5.6 },
  { name: "Michael Pittman Jr.", position: "WR", team: "IND", mean: 11.4, stdDev: 5.4 },
  { name: "Deebo Samuel", position: "WR", team: "WAS", mean: 11.8, stdDev: 5.8 },
  { name: "George Pickens", position: "WR", team: "DAL", mean: 12.6, stdDev: 6.4 },
  { name: "Rashid Shaheed", position: "WR", team: "NO", mean: 9.6, stdDev: 5.6 },
  { name: "Jayden Reed", position: "WR", team: "GB", mean: 11.0, stdDev: 5.6 },
  { name: "Romeo Doubs", position: "WR", team: "GB", mean: 9.4, stdDev: 4.8 },
  { name: "Christian Kirk", position: "WR", team: "HOU", mean: 9.8, stdDev: 4.8 },
  { name: "Keenan Allen", position: "WR", team: "LAC", mean: 11.2, stdDev: 5.0 },
  { name: "Stefon Diggs", position: "WR", team: "NE", mean: 11.6, stdDev: 5.6 },
  { name: "Brandon Aiyuk", position: "WR", team: "SF", mean: 11.8, stdDev: 5.8 },
  { name: "Adam Thielen", position: "WR", team: "CAR", mean: 8.8, stdDev: 4.4 },
  { name: "Tyler Lockett", position: "WR", team: "TEN", mean: 8.4, stdDev: 4.6 },
  { name: "Quentin Johnston", position: "WR", team: "LAC", mean: 9.2, stdDev: 5.4 },
  { name: "Marvin Mims Jr.", position: "WR", team: "DEN", mean: 8.6, stdDev: 5.0 },
  { name: "Alec Pierce", position: "WR", team: "IND", mean: 8.2, stdDev: 5.2 },
  { name: "Dontayvion Wicks", position: "WR", team: "GB", mean: 7.8, stdDev: 4.6 },
  { name: "Cedric Tillman", position: "WR", team: "CLE", mean: 8.0, stdDev: 4.8 },
  { name: "Xavier Legette", position: "WR", team: "CAR", mean: 7.6, stdDev: 4.4 },

  { name: "Colston Loveland", position: "TE", team: "CHI", mean: 8.0, stdDev: 4.2 },
  { name: "Tyler Warren", position: "TE", team: "IND", mean: 8.2, stdDev: 4.4 },
  { name: "Isaiah Likely", position: "TE", team: "BAL", mean: 7.8, stdDev: 4.6 },
  { name: "Cole Kmet", position: "TE", team: "CHI", mean: 7.4, stdDev: 4.0 },
  { name: "Hunter Henry", position: "TE", team: "NE", mean: 7.6, stdDev: 4.0 },
  { name: "Pat Freiermuth", position: "TE", team: "PIT", mean: 7.2, stdDev: 4.0 },
  { name: "Zach Ertz", position: "TE", team: "WAS", mean: 7.8, stdDev: 4.2 },
  { name: "Jonnu Smith", position: "TE", team: "PIT", mean: 8.4, stdDev: 4.6 },
  { name: "Mike Gesicki", position: "TE", team: "CIN", mean: 6.8, stdDev: 3.8 },
  { name: "Chig Okonkwo", position: "TE", team: "TEN", mean: 6.6, stdDev: 3.8 },

  { name: "Jason Myers", position: "K", team: "SEA", mean: 8.2, stdDev: 3.2 },
  { name: "Evan McPherson", position: "K", team: "CIN", mean: 8.4, stdDev: 3.4 },
  { name: "Wil Lutz", position: "K", team: "DEN", mean: 8.6, stdDev: 3.2 },
  { name: "Matt Gay", position: "K", team: "WAS", mean: 7.8, stdDev: 3.2 },
  { name: "Jake Bates", position: "K", team: "DET", mean: 8.8, stdDev: 3.4 },
  { name: "Chase McLaughlin", position: "K", team: "TB", mean: 9.0, stdDev: 3.4 },

  { name: "Cardinals D/ST", position: "DST", team: "ARI", mean: 6.4, stdDev: 4.4 },
  { name: "Buccaneers D/ST", position: "DST", team: "TB", mean: 6.2, stdDev: 4.4 },
  { name: "49ers D/ST", position: "DST", team: "SF", mean: 6.8, stdDev: 4.6 },
  { name: "Cowboys D/ST", position: "DST", team: "DAL", mean: 6.0, stdDev: 4.4 },
  { name: "Jets D/ST", position: "DST", team: "NYJ", mean: 6.6, stdDev: 4.6 },
  { name: "Commanders D/ST", position: "DST", team: "WAS", mean: 5.8, stdDev: 4.2 },
];

export type SeedManager = { name: string; email: string };

export const LEAGUE_ONE_MANAGERS: SeedManager[] = [
  { name: "Hunter Shapiro", email: "hunter@sflinsider.com" },
  { name: "Noah Whitaker", email: "noah@example.com" },
  { name: "Liam Castellano", email: "liam@example.com" },
  { name: "Lance Okafor", email: "lance@example.com" },
  { name: "Marcus Bell", email: "marcus@example.com" },
  { name: "Devin Ramirez", email: "devin@example.com" },
  { name: "Priya Raghavan", email: "priya@example.com" },
  { name: "Tobias Lindqvist", email: "tobias@example.com" },
  { name: "Jordan Pike", email: "jordan@example.com" },
  { name: "Andre Coleman", email: "andre@example.com" },
  { name: "Sofia Marchetti", email: "sofia@example.com" },
  { name: "Wesley Nakamura", email: "wesley@example.com" },
];

export const LEAGUE_TWO_MANAGERS: SeedManager[] = [
  { name: "Hunter Shapiro", email: "hunter@sflinsider.com" },
  { name: "Callum Reyes", email: "callum@example.com" },
  { name: "Miriam Osei", email: "miriam@example.com" },
  { name: "Grant Halloway", email: "grant@example.com" },
  { name: "Emiliano Duarte", email: "emiliano@example.com" },
  { name: "Rhys Donnelly", email: "rhys@example.com" },
  { name: "Kaia Lindstrom", email: "kaia@example.com" },
  { name: "Theo Brennan", email: "theo@example.com" },
  { name: "Isabel Fontaine", email: "isabel@example.com" },
  { name: "Omar Haddad", email: "omar@example.com" },
];

/** Team names rotate year to year, which is exactly why Franchise exists. */
export const TEAM_NAMES: string[] = [
  "The Big Dih",
  "Comeback Szn",
  "Regulation Gentlemen",
  "Dropped Third Down",
  "Fourth and Forgiveness",
  "Backup Plan",
  "The Waiver Wire Warriors",
  "Certified Bust Collectors",
  "Kittle Me This",
  "Hurts So Good",
  "Sunday Scaries",
  "Bye Week Bandits",
  "The Punt Returners",
  "Chubb Rock",
  "Zero RB Truthers",
  "Mahomies & Homies",
  "Autodraft Anonymous",
  "The Injury Report",
  "Garbage Time Heroes",
  "Optimal Lineup Deniers",
  "Ain't No Kelce",
  "Flag Football Enjoyers",
  "The Trade Vetoers",
  "Fumble in the Jungle",
  "Last Place Dynasty",
  "Statistically Eliminated",
  "Points Against Enthusiasts",
  "The Handcuffs",
  "Prime Time Pretenders",
  "Third String Dreams",
  "Red Zone Refugees",
  "Championship Or Bust",
  "Two Yards Short",
  "The Tank Commanders",
  "Practice Squad Legends",
  "Overtime Optimists",
];

export const LEAGUE_ONE = {
  slug: "the-founders-league",
  name: "The Founders League",
  tagline: "Twelve managers. One trophy. Zero forgiveness.",
  description:
    "The original league. Started in a group chat, still running, still argued about every September.",
  accentColor: "#F5C518",
  secondColor: "#0B7A75",
  foundedYear: 2019,
  teamCount: 12,
};

export const LEAGUE_TWO = {
  slug: "sunday-scaries",
  name: "Sunday Scaries",
  tagline: "The work league that got out of hand.",
  description:
    "Ten managers who agreed it would be casual. It has not been casual since week two of the first season.",
  accentColor: "#4D9CFF",
  secondColor: "#9061F9",
  foundedYear: 2021,
  teamCount: 10,
};
